### ISSUE TITLE
Validic::Client.new.get_fitness - NoMethodError: undefined method `[]' for nil:NilClass 

### ISSUE THREAD

**Issue by topher6345** [Validic/validic#22]
Full stack trace

```
/usr/local/rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/summary.rb:6:in `initialize'
/usr/local/rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/utils.rb:10:in `new'
/usr/local/rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/utils.rb:10:in `build_response_attr'
/usr/local/rvm/gems/ruby-2.1.5/gems/validic-0.4.1/lib/validic/rest/fitness.rb:9:in `get_fitness'
/home/hmw-admin/rubyAngular/app/jobs/validic_fetch.rb:25:in `fetch_validic'
/home/hmw-admin/rubyAngular/app/jobs/validic_fetch.rb:16:in `block in perform'
/home/hmw-admin/rubyAngular/app/jobs/validic_fetch.rb:14:in `each'
/home/hmw-admin/rubyAngular/app/jobs/validic_fetch.rb:14:in `perform'
/home/hmw-admin/rubyAngular/lib/tasks/validic.rake:4:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

```ruby
# app/jobs/validic_fetch.rb
class ValidicFetchJob < ActiveJob::Base
  queue_as :default

  def perform
    @client = Validic::Client.new
    @range = { start_date: DateTime.now - 5.minutes }
    %w(fitness weight sleep routine).each do |object|
      @object = object
      fetch_validic
      next unless @validic_response
      create_record
    end
  rescue NoMethodError => e
    Rails.logger.debug e
  end

  private

  def fetch_validic
    res = @client.send(
      "get_#{@object}", @range)
    @validic_response = res.records
  end

  def create_record
    @validic_response.each do |item|
      puts DateTime.now, ValidicModelFactory.create!(item, type)
    end
  end

  def type
    "Validic#{@object.capitalize}".constantize
  end
end

```

I've replicated this in the console it seems that the `get_fitness` method is throwing an exception around here

https://github.com/Validic/validic/blob/master/lib/validic/summary.rb#L5

it seems the `some_hash` argument is coming back nil.

How can I fix this issue? Right now I'm just rescuing the error and logging it.

**Comment by allcentury** [comment]
I'm not sure why it's dying in the initialize method but your variable `@range` is going to return a float.  Anytime you do math on DateTime objects you'll get back a float, ie:

```ruby
DateTime.now - DateTime.new(2015, 07, 21, 16)
=> (15349210727/86400000000)
```

What did you intend `@range` to be equal to?

**Comment by topher6345** [comment]
`@range` is intended to be the options hash, sorry for the bad name.

```ruby
@range = { start_date: DateTime.now - 5.minutes }
 => {:start_date=>Tue, 21 Jul 2015 13:20:50 -0700}
```

```ruby
@range[:start_date].class
 => DateTime
```

It seems that the date calculation is returning a DateTime object.

In the options hash should I be passing a float value to the `start_date` key?

**Comment by topher6345** [comment]
It seems to be a time synchronization issue. The clock on my server is >6 minutes fast and it seems its asking for fitness records in the future

Production Server:

```ruby
DateTime.now
=> Tue, 21 Jul 2015 13:39:11 -0700
```

Local Time: 

```ruby
DateTime.now
=> Tue, 21 Jul 2015 13:33:28 -0700
```

Looks like I found an edge case where start_date is in the future.

I'll talk to my hosting provider about this timing issue.

**Comment by allcentury** [comment]
I'm able to reproduce this locally with:

```ruby
client.get_fitness( {start_date: DateTime.now, end_date: DateTime.now - 5.minutes })
```

The API responds with an invalid date error:

```ruby
{"code"=>406, "message"=>"Not Acceptable", "errors"=>["Invalid date"]}
```

And the gem dies with the same:

```ruby
NoMethodError: undefined method `[]' for nil:NilClass                                                                                       
from /Users/anthonyross/.rvm/gems/ruby-2.2.2@validic/gems/validic-0.4.1/lib/validic/summary.rb:6:in `initialize'
```

I put in a patch to handle InvalidDate errors.
